load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

config_setting(
    name = "fast32bit",
    define_values = {"addr_size": "32"},
)

COPTS_32BIT = [] + select({
    ":fast32bit": ["-DFAST_32BIT"],
    "@platforms//os:macos": [],
})

config_setting(
    name = "openmp_disabled",
    define_values = {"openmp": "disabled"},
)

test_suite(
    name = "tests",
    tests = [
        "api_test",
        "unit_tests",
    ],
)

cc_binary(
    name = "sim",
    srcs = [
        "src/simulation.cc",
    ],
    linkopts = select({
        ":openmp_disabled": [],
        "@bazel_tools//src/conditions:darwin": [],
        "@platforms//os:macos": ["-lgomp"],
    }),
    deps = [
        ":bounded_iaf",
        ":container_cache_sim",
        ":ost_cache_sim",
    ],
)

cc_binary(
    name = "dump_traces",
    srcs = [
        "src/dump_traces.cc",
    ],
    deps = [
        ":cache_sim",
    ],
)

cc_library(
    name = "cache_sim",
    hdrs = [
        "includes/cache_sim.h",
        "includes/sim_factory.h",
        "includes/params.h",
    ],
    copts = COPTS_32BIT,
    includes = ["includes"],
)

cc_library(
    name = "iaf_params",
    hdrs = ["includes/iaf_params.h"],
    copts = COPTS_32BIT,
    includes = ["includes"],
)

cc_library(
    name = "ostree",
    srcs = ["src/ostree.cc"],
    hdrs = ["includes/ostree.h"],
    copts = COPTS_32BIT,
    includes = ["includes"],
)

cc_library(
    name = "ost_cache_sim",
    srcs = ["src/ost_cache_sim.cc"],
    hdrs = ["includes/ost_cache_sim.h"],
    copts = COPTS_32BIT,
    includes = ["includes"],
    deps = [
        ":cache_sim",
        ":ostree",
    ],
)

cc_library(
    name = "container_cache_sim",
    srcs = ["src/container_cache_sim.cc"],
    hdrs = ["includes/container_cache_sim.h"],
    copts = COPTS_32BIT,
    includes = ["includes"],
    deps = [
        ":cache_sim",
        "//container:order_statistic_set",
    ],
)

cc_library(
    name = "increment_and_freeze",
    srcs = [
        "src/increment_and_freeze.cc",
        "src/projection.cc",
    ],
    hdrs = [
        "includes/increment_and_freeze.h",
        "includes/op.h",
        "includes/partition.h",
        "includes/projection.h",
    ],
    copts = COPTS_32BIT + select({
        ":openmp_disabled": [],
        "@bazel_tools//src/conditions:darwin": [],
        "@platforms//os:macos": ["-fopenmp"],
    }),
    includes = ["includes"],
    deps = [
        ":cache_sim",
        ":iaf_params"
    ],
)

cc_library(
    name = "bounded_iaf",
    srcs = ["src/bounded_iaf.cc"],
    hdrs = ["includes/bounded_iaf.h"],
    copts = COPTS_32BIT,
    includes = ["includes"],
    deps = [
        ":iaf_params",
        ":increment_and_freeze",
    ],
)

cc_library(
    name = "iaf_api",
    srcs = ["src/iaf_api.cc"],
    hdrs = ["includes/iaf_api.h"],
    copts = COPTS_32BIT,
    includes = ["includes"],
    deps = [
        ":bounded_iaf",
    ],
)

cc_test(
    name = "unit_tests",
    size = "small",
    srcs = [
        "src/memory_cutoff_tests.cc",
        "src/unit_tests.cc",
    ],
    linkopts = select({
        ":openmp_disabled": [],
        "@bazel_tools//src/conditions:darwin": [],
        "@platforms//os:macos": ["-lgomp"],
    }),
    deps = [
        ":bounded_iaf",
        ":container_cache_sim",
        ":ost_cache_sim",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "api_test",
    srcs = ["src/api_test.cc"],
    copts = COPTS_32BIT,
    linkopts = select({
        ":openmp_disabled": [],
        "@bazel_tools//src/conditions:darwin": [],
        "@platforms//os:macos": ["-lgomp"],
    }),
    deps = [
        ":iaf_api",
    ],
)
